### ISSUE TITLE
Text outside of box

### ISSUE THREAD

**Issue by RealAnthony0001** [UwUYukinekoUwU/Mew-Mew-Escape#1]
**Description**
 - on some resolutions, the dialogue line appears outside of the textbox it's supposed to be in
 
**Reproduction steps**
 - use a laptop with screen resolution 16:10
 - try to activate one of the longer dialogues, like the white cat one
 - longer lines should appear outside of the text box

**Expected behaviour**
 - dialogue stays in the text box, no matter the resolution

**screenshots**
- ![image](https://github.com/UwUYukinekoUwU/Mew-Mew-Escape/assets/39630575/b678f46c-010f-49f8-8e78-2edc0679659b)

**Version**
 - OS: Windows 11 23H2 (arm)
 - Game version: 0.0.1a

**Comment by UwUYukinekoUwU** [comment]
Should be fixed in version 0.0.2a
