### ISSUE TITLE
Bad hitboxes and camera logic

### ISSUE THREAD

**Issue by RealAnthony0001** [UwUYukinekoUwU/Mew-Mew-Escape#3]
**Description**
 - can run outside of the map
 - camera follows in a weird angle

**Reproduction steps**
 - from the entry scene, go left and then down, just like in the video below
 - you should be now out of bounds

**Expected behaviour**
 - a wall stopping you or something

**Video**
- https://github.com/UwUYukinekoUwU/Mew-Mew-Escape/assets/103605032/ecb797f6-6ba4-4b71-93ec-afed272eaa8c

**Version**
 - OS: Windows 11 23H2 (arm)
 - Game version: 0.0.1a

**Comment by UwUYukinekoUwU** [comment]
Fixed in version 0.0.2a
